### ISSUE TITLE
fail to run due to "hnsw" does not exist error

### ISSUE THREAD

**Issue by xinhuitian** [microsoft/MSVBASE#15]
Hello, I followed steps in README, but failed to run the create index sql, getting the following error meg:
```
vectordb=# create index vector_index_1 on t_table using hnsw(vector_1) with(dimension=10,distmethod=l2_distance);
ERROR:  access method "hnsw" does not exist
```
Any idea about how to fix it? thx

**Comment by xinhuitian** [comment]
Do we have a built docker image available to download for test?

**Comment by zqxjjj** [comment]
> Hello, I followed steps in README, but failed to run the create index sql, getting the following error meg:
> 
> ```
> vectordb=# create index vector_index_1 on t_table using hnsw(vector_1) with(dimension=10,distmethod=l2_distance);
> ERROR:  access method "hnsw" does not exist
> ```
> 
> Any idea about how to fix it? thx

Have you executed the command "create extension vectordb" in the example?

**Comment by zqxjjj** [comment]
> Do we have a built docker image available to download for test?

Not for now. But you can build docker image using Dockfile.

**Comment by xinhuitian** [comment]
> > Hello, I followed steps in README, but failed to run the create index sql, getting the following error meg:
> > ```
> > vectordb=# create index vector_index_1 on t_table using hnsw(vector_1) with(dimension=10,distmethod=l2_distance);
> > ERROR:  access method "hnsw" does not exist
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any idea about how to fix it? thx
> 
> Have you executed the command "create extension vectordb" in the example?

@zqxjjj It works after run this, thx :)
