### ISSUE TITLE
Spann is available for now? The source code seems has the index.

### ISSUE THREAD

**Issue by JackTan25** [microsoft/MSVBASE#8]

**Comment by zqxjjj** [comment]
Select Query should be OK. But insert/update/delete operations are not supported after the index is built. 
VBase is integrating SPFresh, then these operations can be supported in SPANN.

**Comment by JackTan25** [comment]
SPFresh can acclerate the SPANN's speed? @zqxjjj

**Comment by JackTan25** [comment]
@mageirakos Hi, can you run the patch script, I get error? @zqxjjj I hope to run this repo without docker.
